name: Download

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: Download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      env:
        START: ${{ secrets.START }}
        END: ${{ secrets.END }}
        SLEEP: ${{ secrets.SLEEP }}
        USER_AGENT: ${{ secrets.USER_AGENT }} 
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: ${{ secrets.BRANCH }}
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # set up git
        git config --global user.email ${EMAIL}
        git config --global user.name ${USERNAME}
        git remote set-url origin https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/nber.git
        sudo apt-get install poppler-utils
        sudo chmod u+x download_paper.sh
        bash download_paper.sh $START $END paper $SLEEP $USER_AGENT
    - name: Commit changes
      run: |
        git add paper/*
        git commit --allow-empty -m "Add paper(s)"
        git pull --rebase origin ${BRANCH}
        git push -u origin ${BRANCH}
