name: Download

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: Download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run script
      env:
        TOTAL: ${{ secrets.TOTAL }}
      run: |
        sudo apt-get install poppler-utils
        python src/download_paper.py --total ${TOTAL}
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: ${{ secrets.BRANCH }}
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        git config --global user.email ${EMAIL}
        git config --global user.name ${USERNAME}
        git remote set-url origin https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/nber.git
        git add paper/*
        git commit -m "Add paper(s)"
        git pull --no-rebase origin ${BRANCH}
        git push -u origin ${BRANCH}
