name: NBER

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: NBER
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        TOTAL: ${{ secrets.TOTAL }}
      run: |
        python src/nber.py --total ${TOTAL}
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: ${{ secrets.BRANCH }}
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        git config --global user.email ${EMAIL}
        git config --global user.name ${USERNAME}
        git remote set-url origin https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/nber.git
        git add data/nber.csv
        git commit -m "Update nber.csv"
        git pull --rebase origin ${BRANCH}
        git push -u origin ${BRANCH}
