name: notebook

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: notebook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install fonts-humor-sans
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rm -rf ~/.cache/matplotlib
    - name: Run script
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/nber.git
        jupyter nbconvert --to notebook --execute index.ipynb
        mv index.nbconvert.ipynb index.ipynb
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git add .
        git commit -m "Updated notebook for use case example"
        git pull --rebase origin main
        git push -u origin main
