name: RePEc

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: RepEc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        python src/repec.py --initial_id 1 --paper 100 --timeout 60 --sleep 1 --user-agent ${USER_AGENT}
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/nber.git
        git add -A
        git diff-index --quiet HEAD || git commit -m "Added new NBER ID done by cron job"
        git pull --rebase origin main
        git push -u origin main
